name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: mkdir dist && echo "test" > dist/test.txt
      - name: Create zip bundle
        run: zip -r EagOS.zip dist
      - name: Publish
        env:
            GITHUB_TOKEN: "${{ secrets.RELEASE_REPO_SECRET }}"
        run: |
            gh release create devbuild EagOS.zip -R https://github.com/EagOS/EagOS-source
