
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-linux
    steps:
      - name: Build
        run: "echo test > dist/test.txt"
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist"
          draft: true
